local_costmap:
   global_frame: odom
   robot_base_frame: base
   update_frequency: 5.0
   publish_frequency: 3.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap